[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd medical-frontend && npm ci"]

[phases.build]
cmds = ["cd medical-frontend && npm run build"]

[start]
cmd = "cd medical-frontend && npm start"

